### ISSUE TITLE
csdn开放平台无法注册

### ISSUE THREAD

**Issue by jigetage** [cyang812/CSDN2HEXO#3]
大佬，我按照你附的链接去注册csdn开放平台，但是链接打不开了。百度完了，还是找不到注册方法。是不是csdn已经关闭注册开放平台了啊？

**Comment by cyang812** [comment]
@jigetage 我也打不开了，看起来是 CSDN 关闭了

**Comment by jigetage** [comment]
> @jigetage 我也打不开了，看起来是 CSDN 关闭了

看来是的，我看看改成不需要登录的方式吧。
